[ {
	"objectInfo" : {
		"father" : "",
		"image" : [],
		"mapX" : 0,
		"mapY" : 0,
		"name" : "test_append_region_name"
	},
	"checked" : false,
	"children" : [],
	"dataIndex" : "",
	"dataItemNum" : 0,
	"expanded" : true,
	"iconCls" : "datatype-subregion",
	"ied" : "",
	"leaf" : true,
	"parentName" : "",
	"text" : "test_append_region_name",
	"unit" : ""
}, {
	"objectInfo" : {
		"father" : "",
		"image" : [],
		"mapX" : 0,
		"mapY" : 0,
		"name" : "test_region_root"
	},
	"checked" : false,
	"children" : [ {
		"objectInfo" : {
			"father" : "test_region_root",
			"image" : [],
			"mapX" : 100,
			"mapY" : 100,
			"name" : "test_modify_region_name"
		},
		"checked" : false,
		"children" : [ {
			"objectInfo" : {
				"name" : "母线3",
				"region" : "test_modify_region_name",
				"remark" : "3",
				"voltage" : 100
			},
			"checked" : false,
			"children" : [ {
				"objectInfo" : null,
				"checked" : false,
				"children" : [ {
					"objectInfo" : null,
					"checked" : false,
					"children" : [],
					"dataIndex" : "",
					"dataItemNum" : 0,
					"expanded" : false,
					"iconCls" : "datatype-busbarboard",
					"ied" : "",
					"leaf" : true,
					"parentName" : "",
					"text" : "板卡0",
					"unit" : ""
				} ],
				"dataIndex" : "",
				"dataItemNum" : 0,
				"expanded" : false,
				"iconCls" : "datatype-none",
				"ied" : "",
				"leaf" : false,
				"parentName" : "",
				"text" : "TEMPLATE59",
				"unit" : ""
			} ],
			"dataIndex" : "",
			"dataItemNum" : 0,
			"expanded" : true,
			"iconCls" : "datatype-busbar",
			"ied" : "",
			"leaf" : false,
			"parentName" : "",
			"text" : "母线3",
			"unit" : ""
		}, {
			"objectInfo" : {
				"name" : "母线1",
				"region" : "test_modify_region_name",
				"remark" : "aaa",
				"voltage" : 1
			},
			"checked" : false,
			"children" : [ {
				"objectInfo" : null,
				"checked" : false,
				"children" : [ {
					"objectInfo" : null,
					"checked" : false,
					"children" : [],
					"dataIndex" : "",
					"dataItemNum" : 0,
					"expanded" : false,
					"iconCls" : "datatype-busbarboard",
					"ied" : "",
					"leaf" : true,
					"parentName" : "",
					"text" : "板卡0",
					"unit" : ""
				} ],
				"dataIndex" : "",
				"dataItemNum" : 0,
				"expanded" : false,
				"iconCls" : "datatype-none",
				"ied" : "",
				"leaf" : false,
				"parentName" : "",
				"text" : "TEMPLATE57",
				"unit" : ""
			} ],
			"dataIndex" : "",
			"dataItemNum" : 0,
			"expanded" : true,
			"iconCls" : "datatype-busbar",
			"ied" : "",
			"leaf" : false,
			"parentName" : "",
			"text" : "母线1",
			"unit" : ""
		} ],
		"dataIndex" : "",
		"dataItemNum" : 0,
		"expanded" : true,
		"iconCls" : "datatype-subregion",
		"ied" : "",
		"leaf" : false,
		"parentName" : "",
		"text" : "test_modify_region_name",
		"unit" : ""
	}, {
		"objectInfo" : {
			"father" : "test_region_root",
			"image" : [],
			"mapX" : 0,
			"mapY" : 0,
			"name" : "test_region_leaf"
		},
		"checked" : false,
		"children" : [ {
			"objectInfo" : {
				"name" : "母线2",
				"region" : "test_region_leaf",
				"remark" : "aaa",
				"voltage" : 1
			},
			"checked" : false,
			"children" : [ {
				"objectInfo" : null,
				"checked" : false,
				"children" : [ {
					"objectInfo" : null,
					"checked" : false,
					"children" : [],
					"dataIndex" : "",
					"dataItemNum" : 0,
					"expanded" : false,
					"iconCls" : "datatype-busbarboard",
					"ied" : "",
					"leaf" : true,
					"parentName" : "",
					"text" : "板卡0",
					"unit" : ""
				} ],
				"dataIndex" : "",
				"dataItemNum" : 0,
				"expanded" : false,
				"iconCls" : "datatype-none",
				"ied" : "",
				"leaf" : false,
				"parentName" : "",
				"text" : "TEMPLATE28",
				"unit" : ""
			} ],
			"dataIndex" : "",
			"dataItemNum" : 0,
			"expanded" : true,
			"iconCls" : "datatype-busbar",
			"ied" : "",
			"leaf" : false,
			"parentName" : "",
			"text" : "母线2",
			"unit" : ""
		}, {
			"objectInfo" : {
				"name" : "母线4",
				"region" : "test_region_leaf",
				"remark" : "4",
				"voltage" : 100
			},
			"checked" : false,
			"children" : [ {
				"objectInfo" : null,
				"checked" : false,
				"children" : [ {
					"objectInfo" : null,
					"checked" : false,
					"children" : [],
					"dataIndex" : "",
					"dataItemNum" : 0,
					"expanded" : false,
					"iconCls" : "datatype-busbarboard",
					"ied" : "",
					"leaf" : true,
					"parentName" : "",
					"text" : "板卡0",
					"unit" : ""
				} ],
				"dataIndex" : "",
				"dataItemNum" : 0,
				"expanded" : false,
				"iconCls" : "datatype-none",
				"ied" : "",
				"leaf" : false,
				"parentName" : "",
				"text" : "TEMPLATE180",
				"unit" : ""
			} ],
			"dataIndex" : "",
			"dataItemNum" : 0,
			"expanded" : true,
			"iconCls" : "datatype-busbar",
			"ied" : "",
			"leaf" : false,
			"parentName" : "",
			"text" : "母线4",
			"unit" : ""
		} ],
		"dataIndex" : "",
		"dataItemNum" : 0,
		"expanded" : true,
		"iconCls" : "datatype-subregion",
		"ied" : "",
		"leaf" : false,
		"parentName" : "",
		"text" : "test_region_leaf",
		"unit" : ""
	} ],
	"dataIndex" : "",
	"dataItemNum" : 0,
	"expanded" : true,
	"iconCls" : "datatype-subregion",
	"ied" : "",
	"leaf" : false,
	"parentName" : "",
	"text" : "test_region_root",
	"unit" : ""
} ];
